### PR TITLE
While swapping plans the name should be also changed (not only 'plan'…

### PR DESCRIPTION
**Pull request by core45**
After swapping plans if you want to check what plan the user currently has you do something this:
`auth()->user()->subscribed('some_plan_name');`
But this will give you wrong result (return true if you put the old plan name)  because while swapping the "plan" is changed but not the "name" which stays as before.
My change fix this problem.

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Makes sense to me, @ciungulete what do you think?

**Comment by sandervanhooft** [comment]
@core45 can you update the matching test as well?

**Comment by ciungulete** [comment]
> Makes sense to me, @ciungulete what do you think?
Yes, good idea.

**Comment by sandervanhooft** [comment]
Here you go!

https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.0.5

**Comment by ronald184** [comment]
Hi, correct me if i'm wrong, but i don't get why this is changed. 
You can check a plan with` user()->subscribedToPlan('plan_name')`, and check if a user has a subscription with `user()->subscribed('subscription_name')`. 
Now you can't have a subscription (product) with different plans as the name will me swapped with the plan on swap (if that makes sense).

**Comment by core45** [comment]
Maybe then we should add something like: user()->swapSubscriptionPlan() and user()->swapSubscriptionName() to add the granularity you need and avoid confusion?

**Comment by FutyWidget** [comment]
@core45 @sandervanhooft I also don't understand why this was changed. I don't think this change has been properly thought through. This change means that the package will no longer work as before. The basic idea of the package has changed because of this. You can create a subscription by $user->newSubscription('main', 'premium');. These are clearly two different parts (name & plan). They are used for different purposes and cannot be treated the same.

Due to this change, our entire subscription implementation can no longer be used.

**Comment by sandervanhooft** [comment]
A plan has a unique reference (`plan`) and a name (`name`). When swapping the plan, both values - as stored on the subscription for convenience - should reflect the change.

Both plan and name were introduced with exactly these method signatures for parity with other PSP implementations.

Consider using multiple plans with the same name if the correct behaviour is bugging you.

**Comment by FutyWidget** [comment]
@sandervanhooft Thanks for your reply. We've been using this package heavily for a while, but maybe we've misunderstood it all along. In our implementation, the plan key(unique) and name are never the same.

With this change, it is no longer possible to use different plans with the same name. The moment a subscription is swapped to another plan (`$subscription->swap($planKey)`), the name is also changed to the unique plan key. As a result, it is no longer possible to use different plans with the same name. And how do I get the current subscription for a user after that? This will not work `$user->subscription('main')`anymore. See below the code that changed:

```
$applyNewSettings = function () use ($newPlan) {
            $this->plan = $newPlan->name();
            $this->name = $newPlan->name();
};
```

**Comment by sandervanhooft** [comment]
Hi @FutyWidget,

Let me look at it one more time. Please revert to the previous version until we have figured it out.

**Comment by sandervanhooft** [comment]
Hi @FutyWidget et al!

We've reverted the swap behavior yesterday evening to allow us for some time to further investigate this issue. If you update to the latest release you should be ok.

**Comment by FutyWidget** [comment]
@sandervanhooft Thanks for your help. That is much appreciated!

**Pull request merged**
