### PR TITLE
Touch up refunds

### PR DESCRIPTION
**Pull request by sandervanhooft**
#118

- Fixes an error in the Refund documentation
- Fixes a bug in processing unlinked refund items

### CODE REVIEW

**Comment by ixperiencenl** [comment]
@sandervanhooft hi Sander, what I am missing in the docs is how the rest of the refunds is going.
I understand that Mollie sends back a status once it is processed, to the webhook. I see that the package then sends a `RefundProcessed` event.

The customer also needs a credit invoice. Is this created automatically? In the views I only see the `receipt.blade.php` which does not include any 'credit invoice' text.

Maybe good to put this in the docs as well.

Thanks for this great package.

**Comment by sandervanhooft** [comment]
Hi @ixperiencenl ,

Good one. Generating the credit order and invoice is handled automatically once the refund is completed. I'll touch up the docs a bit in a moment.

Next time, please open a new issue ticket instead of replying on an existing PR/issue, especially when it's closed :) .

**Comment by ixperiencenl** [comment]
You're absolutely right, but I hate cluttering up the issues list with these kind of things. Anyway, thanks again!

**Comment by sandervanhooft** [comment]
NP, docs should be updated now

**Pull request merged**
