### PR TITLE
Remove money helper from code to stop collision

### PR DESCRIPTION
**Pull request by siegerhansma**
In one of my projects I installed a package that depended on the akaunting/money package. These both use a money helper. The akaunting/money package overrides the money helper in the laravel-cashier-mollie package in my case. 

This pull requests removes the money helper from the client code and directly uses the Money and Currency class. The tests still use the helper, but for users of the package that shouldn't matter.

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Hi @siegerhansma !

Thanks for this PR. Can you point me to the signature of the helper in the colliding package?

**Comment by siegerhansma** [comment]
@sandervanhooft Sure thing, it's over here: https://github.com/akaunting/laravel-money/blob/master/src/helpers.php#L7

**Comment by sandervanhooft** [comment]
Thanks! It appears to me the helper itself isn't removed in this PR?

**Comment by siegerhansma** [comment]
Correct, it's still used in the tests. Should I replace them in the tests and remove the helper?

**Comment by sandervanhooft** [comment]
That would definitely help keeping things consistent :)

**Comment by siegerhansma** [comment]
No problem, I'll update the PR later this week.

**Comment by sandervanhooft** [comment]
Related: #128 #89

**Comment by siegerhansma** [comment]
@sandervanhooft Removed the helper and updated all the tests to use the class instead of the helper. Not sure about the conflict though.

**Review by sandervanhooft — APPROVED** [review]

**Comment by sandervanhooft** [comment]
Looks good to me! Thanks @siegerhansma !

**Comment by RemiHin** [comment]
This was a breaking change in a minor release.
Broke our code because of the missing money function

**Comment by sandervanhooft** [comment]
Hi @RemiHin ,

Thanks for reporting and sorry to hear that. I was under the impression it was only used by Cashier internally. But I now see it's also used by the charge builder. Let me revert this and put the money helper back.

@siegerhansma this will have to wait until next major release.

**Comment by RemiHin** [comment]
hi @sandervanhooft 
We we're able to work around by using the Money and Currency Classes suggested by @siegerhansma, but we might nog be the only people using the helper :) thanks for the quick response

**Comment by sandervanhooft** [comment]
Here you go: https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.5.4

**Pull request merged**
